name: Persistent Telethon Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip screen wget curl jq

    - name: Download required files
      run: |
        wget https://github.com/Kyoura-DE/entotjawa/raw/refs/heads/main/userbot_session.session
        wget https://github.com/Kyoura-DE/entotjawa/raw/refs/heads/main/ubot.py

    - name: Install Telethon
      run: pip3 install telethon

    - name: Run script in screen session
      run: |
        sudo su
        whoami
        screen -dmS telebot bash -c "python3 ubot.py"

    - name: Wait and trigger new workflow
      run: |
        echo "Sleeping for 5 hours 55 minutes..."
        sleep $((60 * 355))  # 5h 55m

        echo "Triggering next workflow run..."
        sleep 5
        echo icikiwir
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer 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" \
          https://api.github.com/repos/Kyoura-DE/entotjawa/actions/workflows/main.yml/dispatches \
          -d '{"ref":"main"}'
          echo kentot

        echo "Workflow finished."
